# Generated by Django 4.2.7 on 2023-11-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='price',
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
