# Generated by Django 5.0 on 2023-12-06 00:59

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_genre_price_game_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
    ]
